SpoonLabs/coming

FeatureList.md
README2.md
pom.xml
src/main/java/fr/inria/coming/core/engine/git/CommitGit.java
src/main/java/prophet4j/Demo.java
src/main/java/prophet4j/defined/FeatureStruct.java
src/main/java/prophet4j/defined/FeatureType.java
src/main/java/prophet4j/defined/RepairStruct.java
src/main/java/prophet4j/defined/RepairType.java
src/main/java/prophet4j/feature/FeatureExtractor.java
src/main/java/prophet4j/feature/FeatureLearner.java
src/main/java/prophet4j/feature/FeatureResolver.java
src/main/java/prophet4j/feature/FeatureVisitor.java
src/main/java/prophet4j/repair/CodeDiffer.java
src/main/java/prophet4j/repair/RepairCandidateGenerator.java
src/main/java/prophet4j/unused/BenchProgram.java
src/main/java/prophet4j/unused/ConfigFile.java
src/main/java/prophet4j/unused/ErrorLocalizer.java
src/main/java/prophet4j/unused/Main.java
src/main/java/prophet4j/unused/RepairSearchEngine.java
src/main/resources/log4j2.properties
src/test/java/fr/inria/coming/spoon/core/MainComingTest.java
src/test/java/fr/inria/coming/spoon/features/CodeFeatureDetectorTest.java
src/test/java/fr/inria/coming/spoon/features/FeaturesOnComingMainTest.java
src/test/java/fr/inria/coming/spoon/patterns/InstanceMiningTest.java
src/test/java/prophet4j/FeatureExtractorTest.java
src/test/java/prophet4j/FeatureLearnerTest.java
src/test/java/prophet4j/FeatureResolverTest.java

As discussed, Prophet4J will be included in this repo.
This time there would be no conflicts or CI errors
- updated code to get compatible with newer version of "org.eclipse.jgit"
- added one repo to make the 1.6-SNAPSHOT of "fr.inria.gforge.spoon.labs" available

include prophet4j

---

src/main/java/fr/inria/coming/main/ComingMain.java
src/main/java/fr/inria/coming/utils/CommandSummary.java
src/test/java/fr/inria/coming/spoon/core/MainComingTest.java
src/test/resources/prophet4j/oldChainSyntax.java

Fixes #28 

---

src/main/java/fr/inria/prophet4j/Demo.java
src/main/java/fr/inria/prophet4j/defined/FeatureLearner.java
src/main/java/fr/inria/prophet4j/defined/Structure.java
src/main/java/fr/inria/prophet4j/defined/extended/ExtendedFeature.java
src/main/java/fr/inria/prophet4j/defined/extended/ExtendedFeatureExtractor.java
src/main/java/fr/inria/prophet4j/defined/extended/ExtendedRepairGenerator.java
src/main/java/fr/inria/prophet4j/defined/extended/util/ExtendedFeatureVisitor.java
src/main/java/fr/inria/prophet4j/defined/extended/util/ExtendedRepairAnalyzer.java
src/main/java/fr/inria/prophet4j/defined/original/OriginalFeature.java
src/main/java/fr/inria/prophet4j/defined/original/OriginalFeatureExtractor.java
src/main/java/fr/inria/prophet4j/defined/original/OriginalRepairGenerator.java
src/main/java/fr/inria/prophet4j/defined/original/util/OriginalFeatureVisitor.java
src/main/java/fr/inria/prophet4j/defined/original/util/OriginalRepairAnalyzer.java
src/main/java/fr/inria/prophet4j/utility/dataport/Cardumen.java
src/main/java/fr/inria/prophet4j/utility/dataport/PGA.java
src/main/java/fr/inria/prophet4j/utility/dataport/SANER.java
src/main/java/fr/inria/prophet4j/utility/dataport/util/Helper.java
src/main/resources/log4j2.properties
src/test/java/fr/inria/prophet4j/EasyTest.java
src/test/java/fr/inria/prophet4j/ExtendedFeatureExtractorTest.java
src/test/java/fr/inria/prophet4j/OriginalFeatureExtractorTest.java

turned to k-fold CV to ensure results reliable
reduced run time consumption

fixed bugs & improved implementation

---

src/main/java/fr/inria/prophet4j/Demo.java
src/main/java/fr/inria/prophet4j/defined/CodeDiffer.java
src/main/java/fr/inria/prophet4j/defined/FeatureLearner.java
src/main/java/fr/inria/prophet4j/defined/Structure.java
src/main/java/fr/inria/prophet4j/defined/extended/ExtendedFeatureCross.java
src/main/java/fr/inria/prophet4j/defined/original/OriginalFeatureCross.java
src/main/java/fr/inria/prophet4j/utility/dataport/Cardumen.java
src/main/java/fr/inria/prophet4j/utility/dataport/PGA.java
src/main/java/fr/inria/prophet4j/utility/dataport/SANER.java
src/main/java/fr/inria/prophet4j/utility/dataport/util/Helper.java

fixed bugs & improved implementation

revised the learner algorithm

---

src/main/java/fr/inria/coming/changeminer/analyzer/instancedetector/DetectorChangePatternInstanceEngine.java
src/main/java/fr/inria/coming/changeminer/entity/ActionType.java
src/main/resources/pattern_specification/pattern_DEL_Parameter.xml
src/main/resources/pattern_specification/pattern_IF_APC.xml
src/main/resources/pattern_specification/pattern_IF_CC.xml
src/main/resources/pattern_specification/pattern_INS_Parameter.xml
src/main/resources/pattern_specification/pattern_INS_X2.xml
src/main/resources/pattern_specification/pattern_MC_DAP.xml
src/main/resources/patterns_examples/case6/Ifcc_false_t.java
src/main/resources/patterns_examples/case6/Ifcc_false_t1.java
src/main/resources/patterns_examples/case6/Ifcc_s.java
src/main/resources/patterns_examples/case6/Ifcc_t.java
src/main/resources/patterns_examples/case7/DEL_Param_false_t.java
src/main/resources/patterns_examples/case7/DEL_Param_s.java
src/main/resources/patterns_examples/case7/DEL_Param_t.java
src/main/resources/patterns_examples/case7/DEL_Param_t1.java
src/main/resources/patterns_examples/case7/INS_Param1_s.java
src/main/resources/patterns_examples/case7/INS_Param1_t.java
src/main/resources/patterns_examples/case7/INS_Param_false_t.java
src/main/resources/patterns_examples/case7/INS_Param_false_t1.java
src/main/resources/patterns_examples/case7/INS_Param_false_t2.java
src/main/resources/patterns_examples/case7/INS_Param_s.java
src/main/resources/patterns_examples/case7/INS_Param_t.java
src/main/resources/patterns_examples/case8/INS_X2_false_t.java
src/main/resources/patterns_examples/case8/INS_X2_s.java
src/main/resources/patterns_examples/case9/Ifapc_false_t.java
src/main/resources/patterns_examples/case9/Ifapc_s.java
src/main/resources/patterns_examples/case9/Ifapc_t.java
src/test/java/fr/inria/coming/spoon/patterns/UnchangedActionTest.java

Implement ActionType.UNCHANGED, ActionType.UNCHANGED_HIGH_PRIORITY
The detail about the priority is [here](https://github.com/SpoonLabs/coming/issues/36#issuecomment-477164997)
I did not come up with better names. Do you have any idea about the name?

Add UNCHANGED action type

---

src/main/java/fr/inria/coming/changeminer/analyzer/instancedetector/DetectorChangePatternInstanceEngine.java
src/main/java/fr/inria/coming/changeminer/analyzer/patternspecification/PatternEntity.java
src/main/java/fr/inria/coming/changeminer/util/PatternXMLParser.java
src/main/resources/diffcases/diffmodif1/RectangularCholeskyDecomposition_s.java
src/main/resources/diffcases/diffmodif1/RectangularCholeskyDecomposition_t.java
src/main/resources/diffcases/diffroleinparent1/1205753_EmbedPooledConnection_0_s.java
src/main/resources/diffcases/diffroleinparent1/1205753_EmbedPooledConnection_0_t.java
src/main/resources/diffcases/diffroleinparent2/1205753_EmbedPooledConnection_0_s.java
src/main/resources/diffcases/diffroleinparent2/1205753_EmbedPooledConnection_0_t.java
src/main/resources/pattern_specification/pattern_modif_if2.xml
src/main/resources/pattern_specification/pattern_modif_if2_role.xml
src/main/resources/pattern_specification/pattern_modif_if_role.xml
src/main/resources/pattern_specification/pattern_test_6_two_upd_if.xml
src/test/java/fr/inria/coming/spoon/patterns/PatternMatchingTest.java

[Feature] new feature in pattern matching: consider Role in parent.

---

docs/features/prophet4j/ExtendedFeatures.md
docs/features/prophet4j/OriginalFeatures.md
docs/features/prophet4j/README.md
src/main/java/fr/inria/prophet4j/Demo.java
src/main/java/fr/inria/prophet4j/dataset/DataManager.java
src/main/java/fr/inria/prophet4j/dataset/PGA.java
src/main/java/fr/inria/prophet4j/feature/Feature.java
src/main/java/fr/inria/prophet4j/feature/FeatureCross.java
src/main/java/fr/inria/prophet4j/feature/enhanced/EnhancedFeatureExtractor.java
src/main/java/fr/inria/prophet4j/feature/extended/ExtendedFeature.java
src/main/java/fr/inria/prophet4j/feature/extended/ExtendedFeatureExtractor.java
src/main/java/fr/inria/prophet4j/feature/original/OriginalFeatureExtractor.java
src/main/java/fr/inria/prophet4j/learner/FeatureLearner.java
src/main/java/fr/inria/prophet4j/learner/RepairEvaluator.java
src/main/java/fr/inria/prophet4j/learner/Tool.java
src/main/java/fr/inria/prophet4j/utility/CodeDiffer.java
src/main/java/fr/inria/prophet4j/utility/Option.java
src/main/java/fr/inria/prophet4j/utility/Structure.java
src/test/java/fr/inria/prophet4j/ExtendedFeatureExtractorTest.java
src/test/java/fr/inria/prophet4j/OriginalFeatureExtractorTest.java

fixed one bug about handling multi-operations diff

---

README.md

README.md: typo fixed

---

docs/features/README.md
src/main/java/fr/inria/coming/codefeatures/CodeFeatureDetector.java
src/main/java/fr/inria/coming/codefeatures/CodeFeatures.java
src/main/java/fr/inria/prophet4j/Demo.java
src/main/java/fr/inria/prophet4j/dataset/DataLoader.java
src/main/java/fr/inria/prophet4j/dataset/DataManager.java
src/main/java/fr/inria/prophet4j/feature/enhanced/EnhancedRepairGenerator.java
src/main/java/fr/inria/prophet4j/feature/extended/ExtendedRepairGenerator.java
src/main/java/fr/inria/prophet4j/feature/original/OriginalRepairGenerator.java
src/main/java/fr/inria/prophet4j/learner/RepairEvaluator.java
src/main/java/fr/inria/prophet4j/utility/CodeDiffer.java
src/main/java/fr/inria/prophet4j/utility/Option.java
src/main/java/fr/inria/prophet4j/utility/Structure.java
src/main/java/fr/inria/prophet4j/utility/Support.java
src/test/java/fr/inria/coming/spoon/features/CodeFeatureDetectorTest.java
src/test/java/fr/inria/coming/spoon/features/FeaturesOnD4jTest.java

fixed bugs and improved implementations

appended Zhongxing's commits

---

.travis.yml
src/main/java/fr/inria/coming/codefeatures/CodeFeatureDetector.java
src/main/java/fr/inria/coming/codefeatures/CodeFeatures.java
src/main/java/fr/inria/prophet4j/Demo.java
src/main/java/fr/inria/prophet4j/dataset/DataManager.java
src/main/java/fr/inria/prophet4j/dataset/PGA.java
src/main/java/fr/inria/prophet4j/feature/enhanced/EnhancedRepairGenerator.java
src/main/java/fr/inria/prophet4j/feature/extended/ExtendedRepairGenerator.java
src/main/java/fr/inria/prophet4j/feature/original/OriginalRepairGenerator.java
src/main/java/fr/inria/prophet4j/learner/FeatureLearner.java
src/main/java/fr/inria/prophet4j/learner/RepairEvaluator.java
src/main/java/fr/inria/prophet4j/learner/Tool.java
src/main/java/fr/inria/prophet4j/utility/CodeDiffer.java
src/main/java/fr/inria/prophet4j/utility/Option.java
src/main/java/fr/inria/prophet4j/utility/Structure.java
src/main/java/fr/inria/prophet4j/utility/Support.java
src/test/java/fr/inria/prophet4j/EasyTest.java
src/test/resources/prophet4j/buggyBaseSecantSolver.java
src/test/resources/prophet4j/buggyMannWhitneyUTest.java
src/test/resources/prophet4j/buggyMockTable.java
src/test/resources/prophet4j/humanMockTable.java
src/test/resources/prophet4j/patchedBaseSecantSolver.java
src/test/resources/prophet4j/patchedMannWhitneyUTest.java

supported handling move-operations of ast-diff
supported handling numerical features of sketch4repair
improved implementations of P4J-learner
appended other optional implementations (not better) of P4J-extractor and P4J-learner
appended Zhongxin's latest commits

improved implementations (I also appended "dist: trusty" to .travis.yml)

---

README.md
src/main/java/fr/inria/coming/core/engine/filespair/FileDiff.java
src/main/java/fr/inria/coming/core/engine/filespair/FilesPairNavigation.java
src/main/java/fr/inria/coming/main/ComingMain.java
src/test/java/fr/inria/coming/spoon/core/MainComingTest.java

- added one test
- added docs
- added implementation
solves #58

"filespair" input format

---

src/main/java/fr/inria/coming/changeminer/analyzer/instancedetector/PatternInstanceAnalyzer.java
src/main/java/fr/inria/coming/core/engine/files/FileNavigationExperiment.java
src/main/java/fr/inria/coming/main/ComingMain.java
src/main/resources/pattern_specification/pattern_INS_IF_RET.xml
src/main/resources/pattern_specification/pattern_test_1_INS_INV.xml
src/test/java/fr/inria/coming/spoon/patterns/InstanceMiningTest.java

allows passing multiple patterns

---

docs/revision_classification/README.md
docs/types.md
src/main/resources/jMutRepairTest/patch1-Closure-7-Nopol2017/patch1-Closure-7-Nopol2017/patch1-Closure-7-Nopol2017_patch1-Closure-7-Nopol2017_s.java
src/main/resources/jMutRepairTest/patch1-Closure-7-Nopol2017/patch1-Closure-7-Nopol2017/patch1-Closure-7-Nopol2017_patch1-Closure-7-Nopol2017_t.java
src/main/resources/repairability/JMutRepair/binary.xml
src/test/java/fr/inria/coming/spoon/repairability/RepairabilityTest.java

[docs] ROLES naming convention

---

src/main/java/fr/inria/coming/core/entities/output/FeaturesOutput.java
src/main/resources/configuration.properties
src/test/java/fr/inria/coming/spoon/core/MainComingTest.java

fix: JSON files are output in features mode

---

README.md
src/main/java/fr/inria/coming/core/engine/RevisionNavigationExperiment.java
src/main/resources/configuration.properties
src/test/java/fr/inria/coming/spoon/core/MainComingTest.java
src/test/java/fr/inria/coming/spoon/repairability/RepairabilityTest.java
src/test/java/fr/inria/coming/spoon/repairability/TestUtills.java

you can change the number of commits analyzed by -parameters min-nb-commits:N

Adding the option to analyze only the last  N commits

---

.buildscript/deploy_to_maven.sh
.buildscript/settings.xml

This reverts commit 956dc7191fb5d660027261c1cf634ab7de475046.

Revert "one more try (#135)"

---

src/main/java/fr/inria/coming/repairability/repairtools/AbstractRepairTool.java

storing tmp data in temporarily created files

---

src/main/java/fr/inria/coming/codefeatures/CodeElementInfo.java
src/main/java/fr/inria/coming/codefeatures/codeanalyze/WholeStatementAnalyzer.java
src/test/java/fr/inria/coming/spoon/features/CodeFeatureDetectorTest.java

process has not variables, the field "FeatureVars" was not in the
result. Now, it has an empty list.

Adding into final results Features missed. For instance, if the line to

---

pom.xml
src/main/java/fr/inria/coming/changeminer/analyzer/DiffEngineFacade.java
src/main/java/fr/inria/coming/changeminer/analyzer/commitAnalyzer/FineGrainDifftAnalyzer.java
src/main/java/fr/inria/coming/main/ComingMain.java
src/main/resources/config-coming.properties
src/main/resources/diffcases/diffcomment1/1205753_EmbedPooledConnection_0_s.java
src/main/resources/diffcases/diffcomment1/1205753_EmbedPooledConnection_0_t.java
src/main/resources/diffcases/diffcomment2/1205753_EmbedPooledConnection_0_s.java
src/main/resources/diffcases/diffcomment2/1205753_EmbedPooledConnection_0_t.java
src/main/resources/diffcases/diffcomment3/RectangularCholeskyDecomposition_s.java
src/main/resources/diffcases/diffcomment3/RectangularCholeskyDecomposition_t.java
src/test/java/fr/inria/coming/spoon/core/MainComingTest.java
src/test/java/fr/inria/coming/spoon/diffanalyzer/DiffCasesTest.java

(that feature is introduced in gumtree-spoon-diff version 1.23)

[feature] add option to process comments

---

pom.xml
src/test/java/fr/inria/coming/spoon/repairability/repairtools/JGenProgTest.java

For this [PR](https://github.com/eclipse/repairnator/pull/1066)
1 test fail. Any tips ? :)

Feat: update spoon core

---

src/test/java/fr/inria/prophet4j/ExtendedFeatureExtractorTest.java

Hi @martinezmatias,
In this PR, I refactor the testing for extended features in P4J which was commented out. This test shows the code changes and the captured features in P4J.
I note that P4J has original and extended features, but they only share a few common names. Most of the features are the same, but in different names, which are confusing. I will work on unifying the names in the following commits.

#185 refactor tests for P4J extended feature

---

src/main/java/fr/inria/coming/utils/EntityTypesInfoResolver.java

[Fix] issue #219:  the file  gumtree-inheritance-relations.txt could not

---

pom.xml
src/main/java/fr/inria/coming/codefeatures/FeatureAnalyzer.java

Not done, but is it how you would do it?

WIP add Automatic diff dissection

---

src/main/java/fr/inria/coming/codefeatures/FeatureAnalyzer.java

Add for the minimal configuration of ADD, this configuration should be enough to compute all the metrics and patterns detection.

Generate unified diff for ADD

---

src/main/java/fr/inria/coming/codefeatures/RepairnatorFeatures.java
src/test/java/fr/inria/coming/spoon/features/RepairnatorFeatureTest.java

Hi Matias,
This commit is the cherry-pick commit of the #238. Please review them, thanks.

updated ODS label from string value to enum

---

src/main/java/fr/inria/coming/codefeatures/FeatureAnalyzer.java
src/main/java/fr/inria/coming/codefeatures/P4JFeatureAnalyzer.java
src/main/java/fr/inria/prophet4j/feature/original/OriginalFeatureExtractor.java
src/main/java/fr/inria/prophet4j/utility/CodeDiffer.java
src/test/java/fr/inria/coming/spoon/features/RepairnatorFeatureTest.java

In this commit, some bugs are fixed:1) null pointer exceptions and 2)P4J features for multiple changed files.

fix ODS no feature generation bug
